on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to check PR description
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set input
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
      #  run: |
#          desc=`gh api \
#            -H "Accept: application/vnd.github+json" \
#            /repos/petrytar/public2/pulls/${PR_NUMBER}`
#          echo "::set-output name=input::$desc"
        run: |
          log=`git log`
          echo ${log}
          echo "input=${log}" >> $GITHUB_OUTPUT
      - name: Check description
        uses: ./ # Uses an action in the root directory
        id: check_desc
        with:
          input: ${{steps.outputs.input}}
          update-changelog: false
      - name: Get the result
        run: echo "Description format is ${{ steps.check_desc.outputs.result }}"
